# Generated by Django 5.1 on 2024-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
