# Generated by Django 5.1 on 2024-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_alter_balance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
