# Generated by Django 5.1 on 2024-09-02 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_alter_balance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='link',
        ),
        migrations.AddField(
            model_name='balance',
            name='link_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
