# Generated by Django 5.1 on 2024-09-02 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_remove_balance_link_balance_link_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Оплачено ли'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='link_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
