# Generated by Django 5.1 on 2024-08-29 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0005_alter_productcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
