# Generated by Django 5.1 on 2024-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0007_productcardimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
