# Generated by Django 5.1 on 2024-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_created_at_course_file_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(null=True, upload_to='course/files'),
        ),
    ]
