# Generated by Django 5.1 on 2024-08-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_file_alter_course_video'),
        ('product_card', '0007_productcardimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_card.productcard', verbose_name='product_card'),
        ),
    ]
