# Generated by Django 5.1 on 2024-08-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='card',
            new_name='product_card',
        ),
    ]
