# Generated by Django 5.1 on 2024-08-30 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_active'),
        ('product_card', '0009_alter_productcard_cap_alter_productcard_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course/files', verbose_name='материал курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен ли курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_description',
            field=models.TextField(verbose_name='описание урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_title',
            field=models.CharField(max_length=140, verbose_name='название урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='product_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_card.productcard', verbose_name='карточка курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course/videos', verbose_name='видео урока'),
        ),
    ]
