# Generated by Django 5.1 on 2024-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='link_to_artstation',
            field=models.URLField(blank=True, null=True, verbose_name='link to artstation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='link_to_behance',
            field=models.URLField(blank=True, null=True, verbose_name='link to behance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='link_to_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='link to instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='link_to_portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='link to portfolio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/user', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
