# Generated by Django 5.1 on 2024-08-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rub',
            field=models.FloatField(blank=True, null=True, verbose_name='rub'),
        ),
    ]
