# Generated by Django 5.1 on 2024-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='rub'),
        ),
    ]
