# Generated by Django 5.1 on 2024-08-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link_to_artstation',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на  artstation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link_to_behance',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка  на behance'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link_to_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на  instagram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link_to_portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на портфолио'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Сумма на счету в рублях'),
        ),
    ]
