# Generated by Django 5.1 on 2024-08-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Сумма на счету в рублях'),
        ),
    ]
