# Generated by Django 5.1 on 2024-08-30 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_courses', '0002_buycourse_product_card_alter_buycourse_user'),
        ('product_card', '0009_alter_productcard_cap_alter_productcard_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycourse',
            name='product_card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_card.productcard', verbose_name='карточка курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buycourse',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_buy_courses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
