# Generated by Django 5.1 on 2024-09-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_courses', '0003_alter_buycourse_product_card_alter_buycourse_user'),
        ('product_card', '0009_alter_productcard_cap_alter_productcard_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycourse',
            name='product_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_card_buy_courses', to='product_card.productcard', verbose_name='карточка курса'),
        ),
    ]
